package biz.pavonis;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 implements Solvable {

	private static final int NUM_LIMIT = 4000000;
	private int product = 0;

	@Override
	public long solve() {
		fibonacci(1, 1);
		return product;
	}

	private int fibonacci(int previous, int current) {
		if (current >= NUM_LIMIT) {
			return current;
		} else {
			if (current % 2 == 0) {
				product += current;
			}
		}
		return fibonacci(current, previous + current);
	}

}
